hash-format = "sha256"

[[files]]
file = "README.md"
hash = "e759333cb2aedad847958c0f00f3864df1ce4f607f12a49303fb1151cec8d526"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "7b5fba1b2499c191160be6b1b01c54ace077ae7d3c5228ae4af4d360e3d0a336"
metafile = true

[[files]]
file = "mods/advancement-count.pw.toml"
hash = "28a682383e4034ccf3678bf0679889ef441728b4dd1ad1acaed8821237371e1d"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "9a9d6bf3715b20cbf83b967e4dd8b77972d1256e52a7b1c2bbfa4122f5acc931"
metafile = true

[[files]]
file = "mods/baguettelib.pw.toml"
hash = "4dac3194a234f244f6b9c754053758d7af758535f50c1a347ff6d0fd05bd94e6"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "95322b6e88dbeba91b5e7a30d6bd011629124ae8aef5bf1b7d1304f12bd4619c"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "93c4acd165a291c6d1e69c27b05b2747afc926b38a414712263fbc95f42da323"
metafile = true

[[files]]
file = "mods/better-combat.pw.toml"
hash = "c403af9a860ca7248b0a8944629f2a4444d5f51fc610718f06418d5c9b19ebdc"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "9b1610cd28c49d34ce2fd760d208fb569f0e20055fee4c81ed4da6489b340312"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "8fde54624913d86f1176cd1086fa485f1a872573dac144347c57cab76596b715"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "8629fe0739a2243641a1a00b103682bcb2741a9295f9eac4c2a2135a867f8442"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "24c6c3fe917ffbcef04e788dec3e003d0ed03433bc00f9cf4f23fe9b85636aa7"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "e7c3b17b228879438c0764720ce082898192468124458b76d1a6519ea54fd30b"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "65c8086d2ec3d39acc7bd36c7a0306ccc43b602b38fa07d13291bc478ef7dfff"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "e002fab16a9b9ef0a35844030339612a38d3c58b0b93e97a34eb43ddc9108be7"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "d901f874a1e09747b8d0d072c38c426eceead1f29c8ba36680f8f0082996b152"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
hash = "8e671fbd3a5460a61073cced391ec08efc6b67d765e49015eea45a1f1db159a0"
metafile = true

[[files]]
file = "mods/crawl.pw.toml"
hash = "349b56aa9ea8284fb89e880941d319ce52e50e51d63084472ea93493cff105b7"
metafile = true

[[files]]
file = "mods/create-aquatic-ambitions.pw.toml"
hash = "13095f719e466c9187ed385ea7b709226da71143cf192a932d8ec7b27e0c7288"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "a10ca44e38b499dd749e8522b51f16815ddbb60483806a58b0845f179b6b8440"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "87ccbd409962ea48348bd005f00a7c68d2add8528cdc6287c83ff52d21dc8c98"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "ed5a88a8d97fe38cca25a42aa1ffcaf51f8f84535f872a9446eff96b92b5722a"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "9f3bd10fad13a1024513590b53976f0c7c9eb404727b3d08fe87ebbf451bcd04"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "637a0f8e81eebbb776d07f7ce32d6b67675000b6259beacec1cbb1b1d730683d"
metafile = true

[[files]]
file = "mods/create-sound-of-steam.pw.toml"
hash = "16a779fbdf47b154eb5ee30cc8ab41df3d3fe18308337824d66bd036c2c24014"
metafile = true

[[files]]
file = "mods/create-storage-neo-forge.pw.toml"
hash = "3783f5fd0ecd78d772ea7a670785303f90a2a6bb60e9e138f65663f064d90974"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "d6043c928c34ce1f4ada544a49193f95c281665cf88d4931e73370ea02870bed"
metafile = true

[[files]]
file = "mods/create_oxidized.pw.toml"
hash = "50a9e0cce66be2ab5f875133d7ce53d0fc6c35d4a5a4fc0e776f10fadeb61c68"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "61e80b0de7d4991cb6ebae3c826d4b51a3e78e18c35f4730e9741603ab7cb18a"
metafile = true

[[files]]
file = "mods/creeper-overhaul.pw.toml"
hash = "cd4c4ec6ef26d2b61e0cb0bdd398e8d528b88ebf739fc0898bc8cb2f7a88debb"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "4c16ee75d3b04443e96d854eec79344293963e9f4beaaf8e7215023e8ef53b88"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "0603752f5a3db14a380597c84cdb80c3b66564a69d8c7f5c4f1d35c4f2a32924"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/enderman-overhaul.pw.toml"
hash = "8efa1757432143004e1958e70f01139ed350e85c9d5842346d30ec32231636de"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "774831f9dc9f530416b2d71ed08d52502dd6ccacbe4bd0d16adbf23701ce12bc"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "3443f52ef7c1f80ae1cedf459b23c38ac78dbe547cf2cc047e62d0cb2331c808"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "c67d73440c55cc47a47ac8987da9cd01de3ad2a8f1480a304355c3e21092d2e4"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
hash = "c22010071589a36869a478fda1eae893adcc15fc9ab9996a195cc6f54333891b"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "44abae510395f12f9ea97b8296b2f72e25f18b9f3f2cc0ee42c0d9afd73fe0b3"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/flw-vanillin.pw.toml"
hash = "cbcaf4a18e45757f17d4a4f36469f879ae024a9fe58b8129d8a42d0faaeada22"
metafile = true

[[files]]
file = "mods/friends-and-foes-forge.pw.toml"
hash = "fe1fafb878b5dafbc23443447f3121971481e4aa98865c5ecf010df2bb7bd2da"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "11c4ac6932c14f3ad5a2c63d7f39eee1e9a2a91ffc079d5bd917c9aa381abdfb"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "960fb33c17aca9c635f99009c1f16d75c312d043e302a599f6ce8040452079e6"
metafile = true

[[files]]
file = "mods/geophilic.pw.toml"
hash = "b8fe9e74e322076dbecdc93be50d5ba6f66015580f44d6ec77510c71fdcff304"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "dbd756dd9bb17e6ecebcf2d7052a67a2da1c7dd378bc2089bc154916080fe031"
metafile = true

[[files]]
file = "mods/hybrid-aquatic.pw.toml"
hash = "34a5443eacca80c00c8b6076064c38a0403dcde9a0590dee2e26a6409de20279"
metafile = true

[[files]]
file = "mods/illager-invasion.pw.toml"
hash = "bf9baef8bb1145e580ae8ee57b285e22838e943c56a96ffb424fd02bf99c468e"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6bdf101d3d5ec8729a8095d5853f80eb925a47c889cd10de6704b20cc7f3c73e"
metafile = true

[[files]]
file = "mods/immersive-armors.pw.toml"
hash = "48db9bdd1c4b427642995c5351af4a7dee203e13310182afbb6c26315341dbd5"
metafile = true

[[files]]
file = "mods/immersive-paintings.pw.toml"
hash = "80b749335d8a885db433930654303ac924de8e3a70071859492dbb7a93faa519"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "8cd8400cb4e2c5ba60c8a359a7b6ff501078d2056eab0aba7f6b0ac77b7a0694"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "5d49dd7272a1418fabed10e3ef9b5c79c3bbb9205d83e79e301c16ad0a0e89e6"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "e8c20c0c77e5df58d1386d8190ee16a957d78d62d361469db0b0c29458bf1e84"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "f8edc1d5fadb1b65f8f869893ec637ec8a5e5f92fb0a7f140e9e62977668f895"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "1e2e7ad3381209e538e57139fd6e952869b409f841a4559d160763cbf3052cca"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "eae3c14c915400de36bf547550f630de727bbf48ae0ce719b99b2ff50ceaab0d"
metafile = true

[[files]]
file = "mods/more-mobs.pw.toml"
hash = "a9191c9338c40f690c3c055e3452bd33617f5e6ccd56c4f2148985ac92e49fa9"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "42805ef7e224873873d190b0363f2a53dae02530553574f29fab92e258bc0470"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "5dc059422613b5645cb00e32d3bfd53de428c4939113d11ce2c844cb54165da6"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "09ba6db54e6f13fafa1e12a9adcd83db9137617d631288579f520ab11b4bfe9a"
metafile = true

[[files]]
file = "mods/opac-bettercommands.pw.toml"
hash = "f56081427335f96ac7e83f479cd57f57ca2d7a28b43187599c60cd3b104d4c54"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "9d4e4bd1007b5529b2b35439d00d74f0554f2bd8ae0d4d72aeab9d8063c60beb"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "73946fc762c8c03bce86fb420893838136413b36fcd49da3a15949de3130456d"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "c83705becd548879473132552de960f9d5975fa0edaeeb2d4665a4e35457423e"
metafile = true

[[files]]
file = "mods/plushie-buddies.pw.toml"
hash = "cd942ef5ed04c687d74bf1788a5df9f373cb42659b6a35631049901db63dff3f"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "152769b5dfbb92a836634e315898b23b6a555c60b6f05ddf38c00085f2b784f6"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "6812c3faa178cd48c65c5b8e7aeef50bc0b63d8e3b2117065d6179a43d8d3649"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "27721caca5a03b743bf25888e1d984142948069dace31453f103f94f7f24d2ce"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "c0b066684294c33972d562e0cb08ea17b2d31bcf86cd1d6c63b8e968f0eac7a2"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "6b91f46291891e725189b0bd54d0db0f66925b1e785bdfa737592dfcf41a79a3"
metafile = true

[[files]]
file = "mods/scribble.pw.toml"
hash = "3ad87fbb20108d7aa5c89759f64d6695e5ec68553f32976f0710bd0a4d34d85b"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "ce9ddada6ffd55a512149cc474c6a453281a997a5fdf1b7b4a2cc73f875e704a"
metafile = true

[[files]]
file = "mods/shoulder-surfing-reloaded.pw.toml"
hash = "fc483943f2da5bff4f1dcd63288656e57edff89c57dbd92da4ba45e1cb477ee5"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "82fa5e74cae0b3f0199f9822f62a976da2dc6ee03deb543d537ce55d36b11fcb"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "6b100c6847b82f48ac150816c2e9ce8fd590a4dc92a49e38634b7f6c6b5a2e71"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "c1e526d3d17cb3563e596d45c7567ed1fe60c31bdc3457f7a747ef8150bd3c1b"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "d193173f0f5dfb4a921d44e29e8d5cee656dd3a40872939069715bb482b66fc9"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "258a77de0a6db4c9ab045cbb240bcf4eac0dbbca3f6bc981fb461e55c247f23f"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "9d4ee074e0a24d53456a1f3e57f2d89d97e37ce378c575c4f15c3dbeb7f137fb"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "15962183bec2468058c70e87aa32e902a08489b0f86741088cdc9aa958ba4931"
metafile = true

[[files]]
file = "mods/tool-trims.pw.toml"
hash = "79d04d954184defd602ce8e5258a1179b45664729d727d5d53e2c1693f05dd00"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "9ce52d07c0c3d146a2a44f8bc187138ce7a5558a4e3ab540c86234702b6de274"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "9d76c3683cfea5c5976823a000eacc9944db9f097894356d2a029cf36642ffa4"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "9b8940ac83dde84cfc59860c6544a4b1194e635786c26bd47dc15eee79e63598"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "64eaf7478e42d5143f4feeee87c56f779f4c3523f9fb06d8342484d36aa4442b"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "d9c0c9209bac0b693af2a7c1e47ffb28d366bad19c91df31dc6d345fa75250a1"
metafile = true

[[files]]
file = "mods/yungs-better-caves.pw.toml"
hash = "9bd04b84287a7ceaae9333f87bb4ca3741506ac7bc2851174f5bc1dd4e3dcc70"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "4c2830674a08ec9f10af13e4d259aa60158bd306a3996d935e678281ec0cb5fd"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "0cc13a86488cf89d2989edc1636fa63c7efa2fe819246d42af35113458d5ba5b"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "c0e40691651465b4eb1037749148c2078123604195e19b582dbef3cd5914e3b1"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "9492d0854c51570bf2a6bace6267262e7573b94c40d721348996617e5d99480a"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "1a33e6d64e88ad59b65d126c6457d582e62724167349ea184eb237435298985e"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "9d9b074b2425fc4f19808b7d6df4a0baeae39a37e909107aaa85004df1a2d195"
metafile = true
