hash-format = "sha256"

[[files]]
file = "mods/better-combat.pw.toml"
hash = "66a784c8c78c18a37fd55cbaeb4d49de609647acc1ca8e47976808a02dab3d15"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "8fde54624913d86f1176cd1086fa485f1a872573dac144347c57cab76596b715"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "bf463928645c586cb57a4e02533ee300af3931cf9db9233dae7efc1826643d41"
metafile = true

[[files]]
file = "mods/create-aquatic-ambitions.pw.toml"
hash = "13095f719e466c9187ed385ea7b709226da71143cf192a932d8ec7b27e0c7288"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "aea6d37ae312cafb92d9456c9b16e7e8406ba03c5dab5c4ade19a204c509ec85"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "87ccbd409962ea48348bd005f00a7c68d2add8528cdc6287c83ff52d21dc8c98"
metafile = true

[[files]]
file = "mods/create-storage-neo-forge.pw.toml"
hash = "346d9496694fc1f9ffcfd558f9e33d3484b9adc46c8e11f16696b659a08bcb7e"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "d6043c928c34ce1f4ada544a49193f95c281665cf88d4931e73370ea02870bed"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "84033f53f275811750cf65ca9ddb5ca0daeced93700ce025d2b834c115ae05f4"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "4c16ee75d3b04443e96d854eec79344293963e9f4beaaf8e7215023e8ef53b88"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "44abae510395f12f9ea97b8296b2f72e25f18b9f3f2cc0ee42c0d9afd73fe0b3"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "960fb33c17aca9c635f99009c1f16d75c312d043e302a599f6ce8040452079e6"
metafile = true

[[files]]
file = "mods/hybrid-aquatic.pw.toml"
hash = "34a5443eacca80c00c8b6076064c38a0403dcde9a0590dee2e26a6409de20279"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "f8edc1d5fadb1b65f8f869893ec637ec8a5e5f92fb0a7f140e9e62977668f895"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "42805ef7e224873873d190b0363f2a53dae02530553574f29fab92e258bc0470"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "c83705becd548879473132552de960f9d5975fa0edaeeb2d4665a4e35457423e"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "6812c3faa178cd48c65c5b8e7aeef50bc0b63d8e3b2117065d6179a43d8d3649"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "6b100c6847b82f48ac150816c2e9ce8fd590a4dc92a49e38634b7f6c6b5a2e71"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "9d4ee074e0a24d53456a1f3e57f2d89d97e37ce378c575c4f15c3dbeb7f137fb"
metafile = true
