name = "Craft Nectar Network"
author = "Sewdohe"
version = "4.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c37378c4a2cbac3100ceb74a692fc8213b173ecdebabdf6c0e77790b2e630661"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
