name = "Craft Nectar Network"
author = "Sewdohe"
version = "4.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21c035bdba25b00cd4c0da5dae7421721ff29282f3f7bcebac6d869f6c3b868b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
