name = "Craft Nectar Network"
author = "Sewdohe"
version = "4.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "264714653a6f510f03d622a8045faa0ed94fd8bd457e3a3fd93d4af3564a1bb6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
