name = "Craft Nectar Network"
author = "Sewdohe"
version = "4.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cffe284df1764013e482a7028f8b79b465fb5f19a20af89569dab79847e1ef3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
