name = "Craft Nectar Network"
author = "Sewdohe"
version = "4.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2477c46d14a97b5adb9644e49586f37e1f4ffb8c5e306ae0ce8254e4ccb902cd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
