name = "Craft Nectar Network"
author = "Sewdohe"
version = "4.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48da2a0f119c7d40db1913b19a278f9b414410e7e31fbc2997c53762c562f609"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
