name = "Craft Nectar Network"
author = "Sewdohe"
version = "4.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c3b61d605593699bca5b677588d4fb988354e448b33e9b2c64676f1134b9b3a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
