name = "Craft Nectar Network"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ea87287225d6820110c5f2ab2637e35c4b1a2d7ba2e575ef9b355cc9bfd8ab9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
